apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  ports:
    - protocol: TCP  
      name: ftps
      port: 20
      targetPort: 20
    - protocol: TCP
      name: filezila
      port: 21
      targetPort: 21 
    - protocol: TCP
      name: passive
      port: 2222
      targetPort: 2222 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 2222